// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"realworld/app/article/internal/biz"
	"realworld/app/article/internal/conf"
	"realworld/app/article/internal/data"
	"realworld/app/article/internal/server"
	"realworld/app/article/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	articleRepo := data.NewArticleRepo(dataData, logger)
	articleUsecase := biz.NewArticleUsecase(articleRepo, logger)
	articleService := service.NewArticleService(articleUsecase)
	grpcServer := server.NewGRPCServer(confData, confServer, articleService, logger)
	httpServer := server.NewHTTPServer(confData, confServer, articleService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
